server:
  port: 30000
spring:
  profiles:
    active: vue
  # 禁用spring mvc freemarker扫描
  freemarker:
    check-template-location: false
  datasource:
    url: jdbc:mysql://www.jihengcc.cn:17336/ypd-test?serverTimezone=Hongkong&useSSL=false&useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**

logging:
  file:
    path: ./code.log
    max-size: 100MB
  level:
    root: info
top:
  bluebirds37:
    # 生成目标文件夹
    result-path: C:\migao\CodeSpaces\scaffold-code-generator\result\
    # 包名称
    package-name: cn.jiheng.ypd
    # 表格前缀，没有就不填写
    table-prefix: t_


